patterns = [
    # General Skills
    {"label": "SKILL", "pattern": "Critical Thinking"},
    {"label": "SKILL", "pattern": "Problem Solving"},
    {"label": "SKILL", "pattern": "Creativity"},
    {"label": "SKILL", "pattern": "Leadership"},
    {"label": "SKILL", "pattern": "Communication"},
    {"label": "SKILL", "pattern": "Teamwork"},
    {"label": "SKILL", "pattern": "Time Management"},
    {"label": "SKILL", "pattern": "Adaptability"},
    {"label": "SKILL", "pattern": "Collaboration"},
    {"label": "SKILL", "pattern": "Emotional Intelligence"},
    {"label": "SKILL", "pattern": "Negotiation"},
    {"label": "SKILL", "pattern": "Decision Making"},
    {"label": "SKILL", "pattern": "Public Speaking"},
    {"label": "SKILL", "pattern": "Presentation Skills"},
    {"label": "SKILL", "pattern": "Analytical Thinking"},
    {"label": "SKILL", "pattern": "Technical Writing"},
    {"label": "SKILL", "pattern": "Research"},
    {"label": "SKILL", "pattern": "Project Planning"},
    {"label": "SKILL", "pattern": "Strategic Thinking"},
    
    # Technology & Engineering
    {"label": "SKILL", "pattern": "Software Development"},
    {"label": "SKILL", "pattern": "Cloud Architecture"},
    {"label": "SKILL", "pattern": "Microservices"},
    {"label": "SKILL", "pattern": "Edge Computing"},
    {"label": "SKILL", "pattern": "Site Reliability Engineering"},
    {"label": "SKILL", "pattern": "Firmware Development"},
    {"label": "SKILL", "pattern": "Virtualization"},
    {"label": "SKILL", "pattern": "Linux System Administration"},
    {"label": "SKILL", "pattern": "Shell Scripting"},
    {"label": "SKILL", "pattern": "Cyber Threat Intelligence"},
    {"label": "SKILL", "pattern": "Data Governance"},
    {"label": "SKILL", "pattern": "ETL Pipelines"},
    {"label": "SKILL", "pattern": "API Development"},
    {"label": "SKILL", "pattern": "Full Stack Development"},
    
    # Healthcare
    {"label": "SKILL", "pattern": "Patient Care"},
    {"label": "SKILL", "pattern": "Medical Coding"},
    {"label": "SKILL", "pattern": "Clinical Research"},
    {"label": "SKILL", "pattern": "Radiology"},
    {"label": "SKILL", "pattern": "Pharmacology"},
    {"label": "SKILL", "pattern": "Nursing"},
    {"label": "SKILL", "pattern": "Emergency Medicine"},
    {"label": "SKILL", "pattern": "Surgery"},
    {"label": "SKILL", "pattern": "Anesthesiology"},
    {"label": "SKILL", "pattern": "Telemedicine"},
    
    # Finance & Business
    {"label": "SKILL", "pattern": "Financial Analysis"},
    {"label": "SKILL", "pattern": "Investment Banking"},
    {"label": "SKILL", "pattern": "Accounting"},
    {"label": "SKILL", "pattern": "Taxation"},
    {"label": "SKILL", "pattern": "Risk Management"},
    {"label": "SKILL", "pattern": "Corporate Finance"},
    {"label": "SKILL", "pattern": "Financial Modeling"},
    {"label": "SKILL", "pattern": "Stock Trading"},
    {"label": "SKILL", "pattern": "Venture Capital"},
    
    # Marketing & Sales
    {"label": "SKILL", "pattern": "SEO"},
    {"label": "SKILL", "pattern": "Content Marketing"},
    {"label": "SKILL", "pattern": "Brand Management"},
    {"label": "SKILL", "pattern": "Lead Generation"},
    {"label": "SKILL", "pattern": "Sales Strategy"},
    {"label": "SKILL", "pattern": "Market Research"},
    {"label": "SKILL", "pattern": "Advertising"},
    {"label": "SKILL", "pattern": "Customer Relationship Management"},
    
    # Education & Training
    {"label": "SKILL", "pattern": "Curriculum Development"},
    {"label": "SKILL", "pattern": "Lesson Planning"},
    {"label": "SKILL", "pattern": "E-learning"},
    {"label": "SKILL", "pattern": "Classroom Management"},
    {"label": "SKILL", "pattern": "Educational Technology"},
    {"label": "SKILL", "pattern": "Online Teaching"},
    
    # Construction & Manufacturing
    {"label": "SKILL", "pattern": "Blueprint Reading"},
    {"label": "SKILL", "pattern": "Welding"},
    {"label": "SKILL", "pattern": "CNC Machining"},
    {"label": "SKILL", "pattern": "Electrical Wiring"},
    {"label": "SKILL", "pattern": "Quality Assurance"},
    {"label": "SKILL", "pattern": "Industrial Design"},
    {"label": "SKILL", "pattern": "HVAC Systems"},
    {"label": "SKILL", "pattern": "Plumbing"},
    {"label": "SKILL", "pattern": "Project Estimation"},
    
    # Arts & Design
    {"label": "SKILL", "pattern": "Graphic Design"},
    {"label": "SKILL", "pattern": "UI/UX Design"},
    {"label": "SKILL", "pattern": "Illustration"},
    {"label": "SKILL", "pattern": "Video Editing"},
    {"label": "SKILL", "pattern": "Photography"},
    {"label": "SKILL", "pattern": "Animation"},
    {"label": "SKILL", "pattern": "3D Modeling"},
    {"label": "SKILL", "pattern": "Motion Graphics"},
    {"label": "SKILL", "pattern": "Sound Design"},
    
    # Others
    {"label": "SKILL", "pattern": "Legal Research"},
    {"label": "SKILL", "pattern": "Contract Negotiation"},
    {"label": "SKILL", "pattern": "Supply Chain Management"},
    {"label": "SKILL", "pattern": "Environmental Science"},

    {"label": "SKILL", "pattern": "Music Composition"},
    {"label": "SKILL", "pattern": "Music Education"},
    {"label": "SKILL", "pattern": "Music History"},
    {"label": "SKILL", "pattern": "Music Theory"},
    {"label": "SKILL", "pattern": "Orchestral Studies"},
    {"label": "SKILL", "pattern": "Piano Performance"},
    {"label": "SKILL", "pattern": "Singing Performance"},
    {"label": "SKILL", "pattern": "Dance Choreography"},
    {"label": "SKILL", "pattern": "Dance Notation"},
    {"label": "SKILL", "pattern": "Acting"},
    {"label": "SKILL", "pattern": "Directing (Theatre)"},
    {"label": "SKILL", "pattern": "Playwrighting"},
    {"label": "SKILL", "pattern": "Film Animation"},
    {"label": "SKILL", "pattern": "Film Criticism"},
    {"label": "SKILL", "pattern": "Filmmaking"},
    {"label": "SKILL", "pattern": "Visual Arts"},
    {"label": "SKILL", "pattern": "Textile Arts"},
    {"label": "SKILL", "pattern": "Calligraphy"},
    {"label": "SKILL", "pattern": "Culinary Arts"},
    {"label": "SKILL", "pattern": "Digital Art"},
    {"label": "SKILL", "pattern": "Graphic Design"},
    {"label": "SKILL", "pattern": "Architecture"},
    {"label": "SKILL", "pattern": "Interior Design"},
    {"label": "SKILL", "pattern": "Fashion Design"},
    {"label": "SKILL", "pattern": "Drawing"},
    {"label": "SKILL", "pattern": "Painting"},
    {"label": "SKILL", "pattern": "Photography"},
    {"label": "SKILL", "pattern": "Sculpture"},

    // History
    {"label": "SKILL", "pattern": "African History"},
    {"label": "SKILL", "pattern": "American History"},
    {"label": "SKILL", "pattern": "Ancient History"},
    {"label": "SKILL", "pattern": "Asian History"},
    {"label": "SKILL", "pattern": "Australian History"},
    {"label": "SKILL", "pattern": "Cultural History"},
    {"label": "SKILL", "pattern": "Economic History"},
    {"label": "SKILL", "pattern": "European History"},
    {"label": "SKILL", "pattern": "Intellectual History"},
    {"label": "SKILL", "pattern": "Latin American History"},
    {"label": "SKILL", "pattern": "Modern History"},
    {"label": "SKILL", "pattern": "Political History"},
    {"label": "SKILL", "pattern": "Religious History"},
    {"label": "SKILL", "pattern": "Russian History"},
    {"label": "SKILL", "pattern": "Scientific History"},
    {"label": "SKILL", "pattern": "Technological History"},
    {"label": "SKILL", "pattern": "World History"},

    // Languages & Literature
    {"label": "SKILL", "pattern": "Linguistics"},
    {"label": "SKILL", "pattern": "English Studies"},
    {"label": "SKILL", "pattern": "Comparative Literature"},
    {"label": "SKILL", "pattern": "Creative Writing"},
    {"label": "SKILL", "pattern": "Poetry Writing"},
    {"label": "SKILL", "pattern": "Prose Writing"},
    {"label": "SKILL", "pattern": "English Literature"},
    {"label": "SKILL", "pattern": "Literary Theory"},
    {"label": "SKILL", "pattern": "Literary Criticism"},
    {"label": "SKILL", "pattern": "American Literature"},
    {"label": "SKILL", "pattern": "British Literature"},

    // Law
    {"label": "SKILL", "pattern": "Administrative Law"},
    {"label": "SKILL", "pattern": "Civil Law"},
    {"label": "SKILL", "pattern": "Common Law"},
    {"label": "SKILL", "pattern": "Contract Law"},
    {"label": "SKILL", "pattern": "Corporate Law"},
    {"label": "SKILL", "pattern": "Criminal Law"},
    {"label": "SKILL", "pattern": "Environmental Law"},
    {"label": "SKILL", "pattern": "Family Law"},
    {"label": "SKILL", "pattern": "International Law"},
    {"label": "SKILL", "pattern": "Labor Law"},
    {"label": "SKILL", "pattern": "Property Law"},
    {"label": "SKILL", "pattern": "Tax Law"},

    // Philosophy
    {"label": "SKILL", "pattern": "Aesthetics"},
    {"label": "SKILL", "pattern": "Epistemology"},
    {"label": "SKILL", "pattern": "Ethics"},
    {"label": "SKILL", "pattern": "Logic"},
    {"label": "SKILL", "pattern": "Metaphysics"},
    {"label": "SKILL", "pattern": "Political Philosophy"},
    {"label": "SKILL", "pattern": "African Philosophy"},
    {"label": "SKILL", "pattern": "Analytic Philosophy"},
    {"label": "SKILL", "pattern": "Continental Philosophy"},
    {"label": "SKILL", "pattern": "Eastern Philosophy"},

    // Religious Studies & Theology
    {"label": "SKILL", "pattern": "Religious History"},
    {"label": "SKILL", "pattern": "Theology"},
    {"label": "SKILL", "pattern": "Biblical Studies"},
    {"label": "SKILL", "pattern": "Canon Law"},
    {"label": "SKILL", "pattern": "Church History"},

    // Social Science (Expanded)
    {"label": "SKILL", "pattern": "Anthropology"},
    {"label": "SKILL", "pattern": "Archaeology"},
    {"label": "SKILL", "pattern": "Economics"},
    {"label": "SKILL", "pattern": "Geography"},
    {"label": "SKILL", "pattern": "Linguistics"},
    {"label": "SKILL", "pattern": "Political Science"},
    {"label": "SKILL", "pattern": "Psychology"},
    {"label": "SKILL", "pattern": "Sociology"},

    // Natural Science (Expanded)
    {"label": "SKILL", "pattern": "Biology"},
    {"label": "SKILL", "pattern": "Chemistry"},
    {"label": "SKILL", "pattern": "Earth Science"},
    {"label": "SKILL", "pattern": "Astronomy"},
    {"label": "SKILL", "pattern": "Physics"},

    // Formal Science
    {"label": "SKILL", "pattern": "Computer Science"},
    {"label": "SKILL", "pattern": "Mathematics"},
    {"label": "SKILL", "pattern": "Statistics"},

    // Applied Science (Expanded)
    {"label": "SKILL", "pattern": "Agriculture"},
    {"label": "SKILL", "pattern": "Architecture"},
    {"label": "SKILL", "pattern": "Design"},
    {"label": "SKILL", "pattern": "Business"},
    {"label": "SKILL", "pattern": "Education"},
    {"label": "SKILL", "pattern": "Engineering"},
    {"label": "SKILL", "pattern": "Environmental Studies"},
    {"label": "SKILL", "pattern": "Forestry"},
    {"label": "SKILL", "pattern": "Family and Consumer Science"},
    {"label": "SKILL", "pattern": "Human Performance"},
    {"label": "SKILL", "pattern": "Recreation"},
    {"label": "SKILL", "pattern": "Journalism"},
    {"label": "SKILL", "pattern": "Media Studies"},
    {"label": "SKILL", "pattern": "Communication"},
    {"label": "SKILL", "pattern": "Law (Applied)"}, 
    {"label": "SKILL", "pattern": "Medicine"}, 
    {"label": "SKILL", "pattern": "Nursing"}, 
    {"label": "SKILL", "pattern": "Pharmacy"}, 
    {"label": "SKILL", "pattern": "Dentistry"},
]
