patterns = [
    # General Skills
    {"label": "SKILL", "pattern": "Critical Thinking"},
    {"label": "SKILL", "pattern": "Problem Solving"},
    {"label": "SKILL", "pattern": "Creativity"},
    {"label": "SKILL", "pattern": "Leadership"},
    {"label": "SKILL", "pattern": "Communication"},
    {"label": "SKILL", "pattern": "Teamwork"},
    {"label": "SKILL", "pattern": "Time Management"},
    {"label": "SKILL", "pattern": "Adaptability"},
    {"label": "SKILL", "pattern": "Collaboration"},
    {"label": "SKILL", "pattern": "Emotional Intelligence"},
    {"label": "SKILL", "pattern": "Negotiation"},
    {"label": "SKILL", "pattern": "Decision Making"},
    {"label": "SKILL", "pattern": "Public Speaking"},
    {"label": "SKILL", "pattern": "Presentation Skills"},
    {"label": "SKILL", "pattern": "Analytical Thinking"},
    {"label": "SKILL", "pattern": "Technical Writing"},
    {"label": "SKILL", "pattern": "Research"},
    {"label": "SKILL", "pattern": "Project Planning"},
    {"label": "SKILL", "pattern": "Strategic Thinking"},
    
    # Technology & Engineering
    {"label": "SKILL", "pattern": "Software Development"},
    {"label": "SKILL", "pattern": "Cloud Architecture"},
    {"label": "SKILL", "pattern": "Microservices"},
    {"label": "SKILL", "pattern": "Edge Computing"},
    {"label": "SKILL", "pattern": "Site Reliability Engineering"},
    {"label": "SKILL", "pattern": "Firmware Development"},
    {"label": "SKILL", "pattern": "Virtualization"},
    {"label": "SKILL", "pattern": "Linux System Administration"},
    {"label": "SKILL", "pattern": "Shell Scripting"},
    {"label": "SKILL", "pattern": "Cyber Threat Intelligence"},
    {"label": "SKILL", "pattern": "Data Governance"},
    {"label": "SKILL", "pattern": "ETL Pipelines"},
    {"label": "SKILL", "pattern": "API Development"},
    {"label": "SKILL", "pattern": "Full Stack Development"},
    
    # Healthcare
    {"label": "SKILL", "pattern": "Patient Care"},
    {"label": "SKILL", "pattern": "Medical Coding"},
    {"label": "SKILL", "pattern": "Clinical Research"},
    {"label": "SKILL", "pattern": "Radiology"},
    {"label": "SKILL", "pattern": "Pharmacology"},
    {"label": "SKILL", "pattern": "Nursing"},
    {"label": "SKILL", "pattern": "Emergency Medicine"},
    {"label": "SKILL", "pattern": "Surgery"},
    {"label": "SKILL", "pattern": "Anesthesiology"},
    {"label": "SKILL", "pattern": "Telemedicine"},
    
    # Finance & Business
    {"label": "SKILL", "pattern": "Financial Analysis"},
    {"label": "SKILL", "pattern": "Investment Banking"},
    {"label": "SKILL", "pattern": "Accounting"},
    {"label": "SKILL", "pattern": "Taxation"},
    {"label": "SKILL", "pattern": "Risk Management"},
    {"label": "SKILL", "pattern": "Corporate Finance"},
    {"label": "SKILL", "pattern": "Financial Modeling"},
    {"label": "SKILL", "pattern": "Stock Trading"},
    {"label": "SKILL", "pattern": "Venture Capital"},
    
    # Marketing & Sales
    {"label": "SKILL", "pattern": "SEO"},
    {"label": "SKILL", "pattern": "Content Marketing"},
    {"label": "SKILL", "pattern": "Brand Management"},
    {"label": "SKILL", "pattern": "Lead Generation"},
    {"label": "SKILL", "pattern": "Sales Strategy"},
    {"label": "SKILL", "pattern": "Market Research"},
    {"label": "SKILL", "pattern": "Advertising"},
    {"label": "SKILL", "pattern": "Customer Relationship Management"},
    
    # Education & Training
    {"label": "SKILL", "pattern": "Curriculum Development"},
    {"label": "SKILL", "pattern": "Lesson Planning"},
    {"label": "SKILL", "pattern": "E-learning"},
    {"label": "SKILL", "pattern": "Classroom Management"},
    {"label": "SKILL", "pattern": "Educational Technology"},
    {"label": "SKILL", "pattern": "Online Teaching"},
    
    # Construction & Manufacturing
    {"label": "SKILL", "pattern": "Blueprint Reading"},
    {"label": "SKILL", "pattern": "Welding"},
    {"label": "SKILL", "pattern": "CNC Machining"},
    {"label": "SKILL", "pattern": "Electrical Wiring"},
    {"label": "SKILL", "pattern": "Quality Assurance"},
    {"label": "SKILL", "pattern": "Industrial Design"},
    {"label": "SKILL", "pattern": "HVAC Systems"},
    {"label": "SKILL", "pattern": "Plumbing"},
    {"label": "SKILL", "pattern": "Project Estimation"},
    
    # Arts & Design
    {"label": "SKILL", "pattern": "Graphic Design"},
    {"label": "SKILL", "pattern": "UI/UX Design"},
    {"label": "SKILL", "pattern": "Illustration"},
    {"label": "SKILL", "pattern": "Video Editing"},
    {"label": "SKILL", "pattern": "Photography"},
    {"label": "SKILL", "pattern": "Animation"},
    {"label": "SKILL", "pattern": "3D Modeling"},
    {"label": "SKILL", "pattern": "Motion Graphics"},
    {"label": "SKILL", "pattern": "Sound Design"},
    
    # Others
    {"label": "SKILL", "pattern": "Legal Research"},
    {"label": "SKILL", "pattern": "Contract Negotiation"},
    {"label": "SKILL", "pattern": "Supply Chain Management"},
    {"label": "SKILL", "pattern": "Environmental Science"},
]
